# Generated by Django 5.1.5 on 2025-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0002_remove_allograph_aspects_delete_aspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
