# Generated by Django 5.1.6 on 2025-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allograph',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
