# Generated by Django 5.1.7 on 2025-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0004_alter_allograph_name_alter_character_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position'},
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, choices=[('Majuscule Letter', 'Majuscule Letter'), ('Minuscule Letter', 'Minuscule Letter'), ('Numeral', 'Numeral'), ('Punctuation', 'Punctuation'), ('Symbol', 'Symbol'), ('Accent', 'Accent')], max_length=16, null=True),
        ),
    ]
