# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0005_alter_position_options_alter_character_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allograph',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Position'},
        ),
    ]
