# Generated by Django 6.0.3 on 2026-04-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0006_alter_allograph_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allographcomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='allographcomponentfeature',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='allographcomponent',
            constraint=models.UniqueConstraint(fields=('allograph', 'component'), name='unique_allograph_component'),
        ),
        migrations.AddConstraint(
            model_name='allographcomponentfeature',
            constraint=models.UniqueConstraint(fields=('allograph_component', 'feature'), name='unique_allograph_component_feature'),
        ),
    ]
