# Generated by Django 6.0.3 on 2026-04-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_structure', '0007_alter_allographcomponent_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllographPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.allograph')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.position')),
            ],
        ),
        migrations.AddField(
            model_name='allograph',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='allographs', through='symbols_structure.AllographPosition', to='symbols_structure.position'),
        ),
        migrations.AddConstraint(
            model_name='allographposition',
            constraint=models.UniqueConstraint(fields=('allograph', 'position'), name='unique_allograph_position'),
        ),
    ]
