# Generated by Django 6.1.1 on 2026-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("symbols_structure", "0008_allographposition_allograph_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Majuscule Letter", "Majuscule Letter"),
                    ("Minuscule Letter", "Minuscule Letter"),
                    ("Numeral", "Numeral"),
                    ("Punctuation", "Punctuation"),
                    ("Symbol", "Symbol"),
                    ("Accent", "Accent"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
