# Generated by Django 6.1 on 2026-09-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0027_reproduction_rights'),
        ('ml', '0002_evaluationrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(db_index=True, max_length=32)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ml_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diplomatic_proposals', to='ml.mljob')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomatic_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sanctio', 'Sanctio'), ('corroboratio', 'Corroboratio'), ('dispositive', 'Dispositive verb'), ('salutation', 'Salutation'), ('notification', 'Notification'), ('other', 'Other')], db_index=True, max_length=24)),
                ('label', models.CharField(max_length=255)),
                ('exemplar', models.TextField(help_text='A representative wording of this formula.')),
                ('published_type', models.CharField(blank=True, default='', help_text="The type in MoA's published formulary typology, where this matches one.", max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulae', to='diplomatic.proposal')),
            ],
            options={
                'verbose_name_plural': 'Formulae',
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CharterEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('granter', 'Granter'), ('beneficiary', 'Beneficiary'), ('witness', 'Witness'), ('place', 'Place'), ('date', 'Date'), ('transaction', 'Transaction type')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('normalised', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_entities', to='manuscripts.imagetext')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='diplomatic.proposal')),
            ],
            options={
                'verbose_name_plural': 'Charter entities',
                'ordering': ['image_text', 'role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('predicate', models.CharField(choices=[('granted_by', 'Granted by'), ('witnessed_by', 'Witnessed by'), ('written_by', 'Written by'), ('beneficiary_of', 'Beneficiary of'), ('located_at', 'Located at')], db_index=True, max_length=24)),
                ('object', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_relations', to='manuscripts.imagetext')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='diplomatic.proposal')),
            ],
            options={
                'ordering': ['image_text', 'predicate', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='FormulaOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='diplomatic.formula')),
                ('image_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_occurrences', to='manuscripts.imagetext')),
            ],
            options={
                'ordering': ['formula', 'image_text'],
                'constraints': [models.UniqueConstraint(fields=('formula', 'image_text'), name='unique_formula_occurrence')],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['pipeline', 'status'], name='proposal_pipeline_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['source_type', 'source_id'], name='proposal_source_idx'),
        ),
        migrations.AddIndex(
            model_name='charterentity',
            index=models.Index(fields=['role', 'name'], name='entity_role_name_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['predicate', 'object'], name='relation_predicate_object_idx'),
        ),
    ]
