# Generated by Django 5.1.7 on 2025-05-19 17:44

import django.db.models.deletion
import djiiif
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_date_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(help_text='A shorthand for the reference (e.g. BL)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('shelfmark', models.CharField(max_length=60, verbose_name='Shelfmark')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', djiiif.IIIFField(max_length=200, upload_to='historical_items')),
                ('locus', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=30)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('library', 'Library'), ('institution', 'Institution'), ('person', 'Person'), ('online resource', 'Online Resource')], max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('agreement', 'Agreement'), ('charter', 'Charter'), ('letter', 'Letter')], max_length=20)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_type', models.CharField(blank=True, choices=[('fhfh', 'FHFH'), ('fhhf', 'FHHF'), ('hffh', 'HFFH'), ('hfhf', 'HFHF'), ('mixed', 'Mixed')], max_length=20, null=True, verbose_name='Hair Type')),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.date')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscripts.itemformat')),
            ],
            options={
                'verbose_name': 'Historical Item',
            },
        ),
        migrations.CreateModel(
            name='CatalogueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('url', models.URLField(null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.bibliographicsource')),
                ('historical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_numbers', to='manuscripts.historicalitem', verbose_name='Historical Item')),
            ],
            options={
                'verbose_name': 'Catalogue Number',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('historical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='manuscripts.historicalitem', verbose_name='Historical Item')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.bibliographicsource')),
            ],
            options={
                'verbose_name': 'Description',
            },
        ),
        migrations.CreateModel(
            name='ImageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('Transcription', 'Transcription'), ('Translation', 'Translation')], max_length=13)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Live', 'Live')], max_length=6)),
                ('item_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='manuscripts.itemimage')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_label', models.CharField(blank=True, default='', help_text='A custom label for this part. If blank the shelfmark will be used as a label.', max_length=80)),
                ('current_item_locus', models.CharField(blank=True, default='', help_text='the location of this part in the Current Item', max_length=30, verbose_name='Locus')),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscripts.currentitem')),
                ('historical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.historicalitem', verbose_name='Historical Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manuscripts.itempart'),
        ),
        migrations.AddField(
            model_name='currentitem',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.repository'),
        ),
    ]
