# Generated by Django 5.1.5 on 2025-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempart',
            name='current_item_locus',
            field=models.CharField(blank=True, default='', help_text='the location of this part in the Current Item', max_length=30, verbose_name='Locus'),
        ),
        migrations.AddField(
            model_name='itempart',
            name='custom_label',
            field=models.CharField(blank=True, default='', help_text='A custom label for this part. If blank the shelfmark will be used as a label.', max_length=80),
        ),
    ]
