# Generated by Django 5.1.6 on 2025-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_bibliographicsource_alter_historicalitem_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='date',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='locus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
