# Generated by Django 5.1.6 on 2025-03-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('manuscripts', '0004_remove_historicalitem_date_alter_itemimage_locus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.date'),
        ),
    ]
