# Generated by Django 5.1.6 on 2025-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_historicalitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='locus',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
