# Generated by Django 5.1.7 on 2025-03-21 00:09

import djiiif
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_alter_itemimage_locus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=djiiif.IIIFField(max_length=200, upload_to='historical_items'),
        ),
    ]
