# Generated by Django 5.1.7 on 2025-05-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0008_remove_historicalitem_issuer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloguenumber',
            options={'verbose_name': 'Catalogue Number'},
        ),
        migrations.AlterModelOptions(
            name='historicalitem',
            options={'verbose_name': 'Historical Item'},
        ),
        migrations.AlterModelOptions(
            name='historicalitemdescription',
            options={'verbose_name': 'Description'},
        ),
        migrations.AlterField(
            model_name='cataloguenumber',
            name='historical_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_numbers', to='manuscripts.historicalitem', verbose_name='Historical Item'),
        ),
        migrations.AlterField(
            model_name='currentitem',
            name='shelfmark',
            field=models.CharField(max_length=60, verbose_name='str, "Shelfmark"'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('fhfh', 'FHFH'), ('fhhf', 'FHHF'), ('hffh', 'HFFH'), ('hfhf', 'HFHF'), ('mixed', 'Mixed')], max_length=20, null=True, verbose_name='Hair Type'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='type',
            field=models.CharField(choices=[('agreement', 'Agreement'), ('charter', 'Charter'), ('letter', 'Letter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalitemdescription',
            name='historical_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='manuscripts.historicalitem', verbose_name='Historical Item'),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='current_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscripts.currentitem'),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='historical_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.historicalitem', verbose_name='Historical Item'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('library', 'Library'), ('institution', 'Institution'), ('person', 'Person'), ('online resource', 'Online Resource')], max_length=30, null=True),
        ),
    ]
