# Generated by Django 6.0.1 on 2026-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0009_alter_cataloguenumber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitem',
            name='shelfmark',
            field=models.CharField(max_length=60, verbose_name='Shelfmark'),
        ),
    ]
