# Generated by Django 5.1.7 on 2025-05-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manuscripts', '0009_alter_cataloguenumber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
