# Generated by Django 6.0.2 on 2026-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscripts", "0010_alter_currentitem_shelfmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="locus",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
