# Generated by Django 6.0.1 on 2026-02-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0010_alter_currentitem_shelfmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Live', 'Live')], max_length=16),
        ),
        migrations.AlterField(
            model_name='imagetext',
            name='type',
            field=models.CharField(choices=[('Transcription', 'Transcription'), ('Translation', 'Translation')], max_length=32),
        ),
    ]
