# Generated by Django 5.1.7 on 2025-05-19 18:14

import apps.manuscripts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manuscripts', '0010_alter_itemimage_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='current_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='current_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='original_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='original_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='content_type',
            field=models.ForeignKey(default=apps.manuscripts.models.get_default_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
