# Generated by Django 6.0.1 on 2026-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0011_alter_imagetext_status_alter_imagetext_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Live', 'Live'), ('Reviewed', 'Reviewed')], max_length=16),
        ),
    ]
