# Generated by Django 5.1.7 on 2025-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0011_historicalitem_current_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
