# Generated by Django 6.0.1 on 2026-02-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0010_imagetext_language_imagetext_created_imagetext_modified'),
        ('manuscripts', '0011_alter_itemimage_locus'),
        ('manuscripts', '0012_alter_imagetext_status'),
    ]

    operations = [
    ]
