# Generated by Django 5.1.7 on 2025-05-19 18:36

import apps.manuscripts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manuscripts', '0012_historicalitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='content_type',
            field=models.ForeignKey(default=apps.manuscripts.models.get_default_content_type, limit_choices_to={'model__in': ('ItemPart', 'HistoricalItem')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
