# Generated by Django 6.0.2 on 2026-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0013_merge_20260214_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitem',
            name='shelfmark',
            field=models.CharField(max_length=60, verbose_name='str, "Shelfmark"'),
        ),
    ]
