# Generated by Django 5.1.7 on 2025-05-19 18:40

import djiiif
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0013_alter_itemimage_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=djiiif.IIIFField(blank=True, max_length=200, null=True, upload_to='historical_items'),
        ),
    ]
