# Generated by Django 6.0.2 on 2026-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0014_alter_currentitem_shelfmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitem',
            name='shelfmark',
            field=models.CharField(max_length=60, verbose_name='Shelfmark'),
        ),
    ]
