# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0015_alter_currentitem_shelfmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographicsource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cataloguenumber',
            options={'ordering': ['number'], 'verbose_name': 'Catalogue Number'},
        ),
        migrations.AlterModelOptions(
            name='currentitem',
            options={'ordering': ['repository', 'shelfmark']},
        ),
        migrations.AlterModelOptions(
            name='historicalitem',
            options={'ordering': ['id'], 'verbose_name': 'Historical Item'},
        ),
        migrations.AlterModelOptions(
            name='historicalitemdescription',
            options={'ordering': ['id'], 'verbose_name': 'Description'},
        ),
        migrations.AlterModelOptions(
            name='imagetext',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='itemformat',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['item_part', 'locus']},
        ),
        migrations.AlterModelOptions(
            name='itempart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name'], 'verbose_name_plural': 'Repositories'},
        ),
    ]
