# Generated by Django 6.0.5 on 2026-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0019_imagetext_review_assignee_statustransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetext',
            name='content_dpt_legacy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
