# Generated by Django 6.0.6 on 2026-06-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_editevent_target_type'),
        ('manuscripts', '0021_historicalitemdateassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.date'),
        ),
    ]
