# Generated by Django 6.0.7 on 2026-07-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0022_alter_historicalitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsDescArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('msIdentifier', 'msIdentifier'), ('msContents', 'msContents'), ('physDesc', 'physDesc'), ('history', 'history')], max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msdesc_areas', to='manuscripts.itempart')),
            ],
            options={
                'ordering': ['item_part', 'area'],
                'constraints': [models.UniqueConstraint(fields=('item_part', 'area'), name='msdescarea_one_per_area_per_part')],
            },
        ),
    ]
