# Generated by Django 6.0.7 on 2026-07-26 14:55
#
# ROADMAP Phase H.11 — the TEI cutover. Drops the retention column added in
# 0020, ending the reversible window: after this, the data-dpt HTML exists only
# as `tei_to_data_dpt(content)` output, and `migrate_imagetext_to_tei` has no
# `--reverse`. Reversing this migration restores an empty column, not the data.
#
# Run `python manage.py verify_tei_cutover` against the target database first —
# it exits non-zero unless dropping the column provably loses nothing.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0023_msdescarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetext',
            name='content_dpt_legacy',
        ),
    ]
