# Generated by Django 6.1 on 2026-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0024_merge_itemimage_metadata_msdescarea'),
        ('manuscripts', '0024_remove_imagetext_content_dpt_legacy'),
    ]

    operations = [
    ]
