# Generated by Django 6.1 on 2026-08-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0026_remove_itemimage_technical_metadata'),
        ('manuscripts', '0027_reproduction_rights'),
    ]

    operations = [
    ]
