# Generated by Django 6.1.1 on 2026-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscripts", "0028_imagetext_content_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemformat",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
