# Generated by Django 6.1.1 on 2026-09-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0029_alter_itemformat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitem',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manuscripts.repository'),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='current_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manuscripts.currentitem'),
        ),
    ]
