# Generated by Django 5.1.5 on 2025-01-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        ('symbols_structure', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='positions',
            field=models.ManyToManyField(related_name='graphs', to='symbols_structure.position'),
        ),
    ]
