# Generated by Django 6.0.1 on 2026-02-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_graph_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='annotation_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('text', 'Text'), ('editorial', 'Editorial'), ('unknown', 'Unknown')], db_index=True, max_length=20, null=True),
        ),
    ]
