# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_graph_annotation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['id']},
        ),
    ]
