# Generated by Django 6.0.3 on 2026-04-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_alter_graph_options'),
        ('symbols_structure', '0007_alter_allographcomponent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphcomponent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='graphcomponent',
            constraint=models.UniqueConstraint(fields=('graph', 'component'), name='unique_graph_component'),
        ),
    ]
