# Generated by Django 6.0.3 on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0005_alter_graphcomponent_unique_together_and_more"),
        ("scribes", "0008_alter_hand_options_alter_scribe_options_and_more"),
        ("symbols_structure", "0008_allographposition_allograph_positions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="internal_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="graph",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="graph",
            name="allograph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="symbols_structure.allograph",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="hand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scribes.hand",
            ),
        ),
        migrations.AddConstraint(
            model_name="graph",
            constraint=models.CheckConstraint(
                condition=models.Q(("annotation_type", "editorial"))
                | (models.Q(("allograph__isnull", False)) & models.Q(("hand__isnull", False))),
                name="graph_editorial_or_required_allograph_hand",
            ),
        ),
    ]
