# Generated by Django 6.0.5 on 2026-05-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_graph_text_type_check_constraint'),
        ('symbols_structure', '0008_allographposition_allograph_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='graphs', to='symbols_structure.position'),
        ),
    ]
