# Generated by Django 6.0.6 on 2026-06-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_graph_created_alter_graph_positions'),
        ('symbols_structure', '0008_allographposition_allograph_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='allograph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='symbols_structure.allograph'),
        ),
    ]
