# Generated by Django 6.1 on 2026-08-28 12:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_graph_deleted_at_graph_deleted_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='graph',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
