# Generated by Django 5.1.7 on 2025-05-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_date_options'),
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('scriptorium', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.date')),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manuscripts.itempart')),
                ('item_part_images', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('item_part', models.F('item_part'))), related_name='hands', to='manuscripts.itemimage')),
                ('scribe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scribes.scribe')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scribes.script')),
            ],
        ),
    ]
