# Generated by Django 5.1.6 on 2025-02-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='item_part_images',
        ),
        migrations.AlterField(
            model_name='hand',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hand',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hand',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scribes.script'),
        ),
        migrations.DeleteModel(
            name='HandToItemPartImages',
        ),
    ]
