# Generated by Django 5.1.6 on 2025-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_bibliographicsource_alter_historicalitem_date_and_more'),
        ('scribes', '0002_remove_hand_item_part_images_alter_hand_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='item_part_images',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('item_part', models.F('item_part'))), related_name='hands', to='manuscripts.itemimage'),
        ),
    ]
