# Generated by Django 5.1.6 on 2025-03-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0003_hand_item_part_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='date',
        ),
    ]
