# Generated by Django 5.2.1 on 2025-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0005_hand_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribe',
            name='period',
        ),
        migrations.AlterField(
            model_name='scribe',
            name='scriptorium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
