# Generated by Django 5.2.1 on 2025-06-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_date_options'),
        ('scribes', '0006_remove_scribe_period_alter_scribe_scriptorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.date'),
        ),
    ]
