# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0007_scribe_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scribe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['name']},
        ),
    ]
