# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scribes", "0008_alter_hand_options_alter_scribe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Prefer this hand as the default assignment hand for its item/image.",
            ),
        ),
        migrations.AddField(
            model_name="hand",
            name="num",
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                help_text="Legacy DigiPal hand display order. Lower values are shown first.",
                verbose_name="Display order",
            ),
        ),
        migrations.AddField(
            model_name="hand",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Higher values make this hand preferred for default assignment.",
            ),
        ),
        migrations.AlterModelOptions(
            name="hand",
            options={
                "ordering": ["item_part", "-is_default", "-priority", "num", "name", "id"],
            },
        ),
    ]
