# Generated by Django 6.1 on 2026-08-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0010_alter_hand_date_alter_hand_item_part_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
