# Generated by Django 6.1 on 2026-08-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0011_alter_hand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
