# Generated by Django 6.1 on 2026-08-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0024_remove_imagetext_content_dpt_legacy'),
        ('scribes', '0014_hand_place_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='scribes.hand')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hand_descriptions', to='manuscripts.bibliographicsource')),
            ],
            options={
                'verbose_name': 'Hand description',
                'ordering': ['id'],
            },
        ),
    ]
