# Generated by Django 6.0.2 on 2026-02-09 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselitem",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Full URL or relative path (e.g. /about).",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(https?://.+|/.*)$",
                        "Enter a full URL or a relative path starting with /.",
                    )
                ],
            ),
        ),
    ]
