paths:
  /api/v1/scribes/{id}/:
    get:
      operationId: scribes-details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scribe'
      tags:
        - scribes
  /api/v1/hands/:
    get:
      operationId: hands-list
      parameters:
        - name: item_image
          in: query
          required: false
          schema:
            type: integer
        - name: scribe
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hand'
      tags:
        - scribes
  /api/v1/hands/{id}/:
    get:
      operationId: hands-details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hand'
      tags:
        - scribes
  /api/v1/search/scribes/facets/:
    get:
      operationId: search-scribes-facets
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  fields: 
                    type: object
                    properties:
                      __facet_name__:
                        type: array
                        items:
                          type: object
                          properties:
                            text:
                              type: string
                            count:
                              type: integer
                            narrow_url:
                              type: string
                  dates:
                    type: object
                  queries:
                    type: object
                  objects:
                    type: object
                    properties:
                      count:
                        type: integer
                      next:
                        type: string
                      previous:
                        type: string
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/ScribeSearchResult'
      tags:
        - search
  /api/v1/search/hands/facets/:
    get:
      operationId: search-hands-facets
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  fields: 
                    type: object
                    properties:
                      __facet_name__:
                        type: array
                        items:
                          type: object
                          properties:
                            text:
                              type: string
                            count:
                              type: integer
                            narrow_url:
                              type: string
                  queries:
                    type: object
                  objects:
                    type: object
                    properties:
                      count:
                        type: integer
                      next:
                        type: string
                      previous:
                        type: string
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/HandSearchResult'
      tags:
        - search
  /api/v1/management/scribes/scribes/:
    get:
      operationId: management-scribes-list
      security:
        - api_key: []
      responses:
        200:
          description: List scribes for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScribeManagementItem'
      tags:
        - scribes-management
  /api/v1/management/scribes/hands/:
    get:
      operationId: management-hands-list
      security:
        - api_key: []
      responses:
        200:
          description: List hands for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HandManagementItem'
      tags:
        - scribes-management
  /api/v1/management/scribes/scripts/:
    get:
      operationId: management-scripts-list
      security:
        - api_key: []
      responses:
        200:
          description: List scripts for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
      tags:
        - scribes-management
  /api/v1/management/scribes/get_item_images/:
    get:
      operationId: management-get-item-images
      security:
        - api_key: []
      parameters:
        - name: item_part_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List item images for selected item part.
      tags:
        - scribes-management
components:
  schemas:
    ScribeSearchResult:
      type: object
      properties:
        name:
          type: string
        period:
          type: string
        scriptorium:
          type: string
    HandSearchResult:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
        place:
          type: string
        description:
          type: string
        repository_name:
          type: string
        repository_city:
          type: string
        shelfmark:
          type: string
        catalogue_numbers:
          type: array
          items:
            type: string
    Idiograph:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        character:
          type: string
    Scribe:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        period:
          type: string
        scriptorium:
          type: string
        idiographs:
          type: array
          items:
            $ref: '#/components/schemas/Idiograph'
    Hand:
      type: object
      properties:
        name:
          type: string
        script_id:
          type: string
        manuscript_id:
          type: integer
        scribe_id:
          type: integer
    ScribeManagementItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        period:
          type: integer
          nullable: true
        period_display:
          type: string
          nullable: true
        scriptorium:
          type: string
          nullable: true
        hand_count:
          type: integer
    HandManagementItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        scribe:
          type: integer
        scribe_name:
          type: string
        item_part:
          type: integer
        item_part_display:
          type: string
        script:
          type: integer
          nullable: true
        script_name:
          type: string
          nullable: true
        date:
          type: integer
          nullable: true
        date_display:
          type: string
          nullable: true
        place:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        item_part_images:
          type: array
          items:
            type: integer
        
    
tags:
  - name: scribes
  - name: scribes-management
