paths:
  /api/v1/manuscripts/graphs/:
    get:
      operationId: graphs-list
      summary: List all annotations or filter by item_image and allograph
      parameters:
        - in: query
          name: item_image
          schema:
            type: integer
          required: false
        - in: query
          name: allograph
          schema:
            type: integer
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Graph'
      tags:
        - Annotations
    post:
      operationId: graphs-create
      summary: Create a new annotation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Graph'
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
      tags:
        - Annotations
components:
  schemas:
    GraphSearchResult:
      type: object
      properties:
        id:
          type: integer
        item_image:
          type: integer
        annotation:
          type: object
        allograph:
          type: integer
        hand:
          type: integer
        graphcomponent_set:
          type: array
          items:
            type: object
            properties:
              component:
                type: integer
              features:
                type: array
                items:
                  type: integer
        positions:
          type: array
          items:
            type: integer
    Graph:
      type: object
      properties:
        id:
          type: integer
        item_image:
          type: integer
        annotation:
          type: object
        allograph:
          type: integer
        hand:
          type: integer
        graphcomponent_set:
          type: array
          items:
            type: object
            properties:
              component:
                type: integer
              features:
                type: array
                items:
                  type: integer
        positions:
          type: array
          items:
            type: integer
          example: [1, 2, 3]
  
tags:
  - name: Annotations
