# Generated by Django 5.1.6 on 2025-03-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('min_weight', models.IntegerField(help_text='The lower bound of the date range', verbose_name='Minimum weight')),
                ('max_weight', models.IntegerField(help_text='The upper bound of the date range', verbose_name='Maximum weight')),
            ],
        ),
    ]
