# Generated by Django 5.1.7 on 2025-05-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Date'},
        ),
    ]
