# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_date_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date'], 'verbose_name': 'Date'},
        ),
    ]
