# Generated by Django 6.0.6 on 2026-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_date_assessment_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editevent',
            name='target_type',
            field=models.CharField(max_length=64),
        ),
    ]
