# Generated by Django 6.0.6 on 2026-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_editevent_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Labels',
                'verbose_name_plural': 'Site Labels',
            },
        ),
    ]
