# Generated by Django 6.0.7 on 2026-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_sitelabel_per_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("status_changed", "Status changed"),
                    ("commented", "Commented"),
                    ("impersonated", "Impersonated"),
                ],
                max_length=24,
            ),
        ),
    ]
