# Generated by Django 6.0.6 on 2026-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_seed_sitelabels_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('historicalItem', 'Historical Item'), ('catalogueNumber', 'Catalogue Number'), ('position', 'Position'), ('date', 'Date'), ('appManuscripts', 'App Name: Manuscripts'), ('fieldHairType', 'Field: Hair Type'), ('fieldShelfmark', 'Field: Shelfmark'), ('fieldDateMinWeight', 'Field: Date Min Weight'), ('fieldDateMaxWeight', 'Field: Date Max Weight'), ('searchCategoryImages', 'Search Category: Images'), ('searchCategoryScribes', 'Search Category: Scribes'), ('searchCategoryHands', 'Search Category: Hands'), ('searchCategoryGraphs', 'Search Category: Graphs'), ('searchCategoryTexts', 'Search Category: Texts'), ('searchCategoryClauses', 'Search Category: Clauses'), ('searchCategoryPeople', 'Search Category: People'), ('searchCategoryPlaces', 'Search Category: Places'), ('siteTitle', 'Site Title'), ('siteTagline', 'Site Tagline'), ('footerLine1', 'Footer Line 1'), ('footerLine2', 'Footer Line 2'), ('footerBottomLine', 'Footer Bottom Line')], max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict, help_text='Value per language, e.g. {"en": "...", "fr": "..."}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Label',
                'verbose_name_plural': 'Site Labels',
                'ordering': ['key'],
            },
        ),
    ]
