# Generated by Django 6.1 on 2026-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_editevent_action'),
        ('common', '0010_seed_log_level_setting'),
        ('common', '0010_seed_site_features'),
    ]

    operations = [
    ]
