# Generated by Django 6.0.7 on 2026-08-12 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_seed_log_level_setting"),
        ("common", "0010_seed_site_features"),
    ]

    operations = []
