# Generated by Django 6.1 on 2026-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_seed_sitelabel_german'),
        ('common', '0012_alter_editevent_action'),
    ]

    operations = [
    ]
