# Generated by Django 6.1 on 2026-08-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_editevent_action'),
        ('common', '0013_merge_20260826_1201'),
    ]

    operations = [
    ]
