# Generated by Django 6.1 on 2026-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_editevent_action'),
        ('common', '0012_place'),
        ('common', '0014_seed_theme_colors'),
    ]

    operations = [
    ]
