# Generated by Django 6.1 on 2026-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_merge_20260828_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status changed'), ('commented', 'Commented'), ('impersonated', 'Impersonated'), ('trashed', 'Trashed'), ('restored', 'Restored')], max_length=24),
        ),
    ]
