# Generated by Django 6.1 on 2026-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_merge_20260828_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status changed'), ('commented', 'Commented'), ('trashed', 'Trashed'), ('restored', 'Restored'), ('impersonated', 'Impersonated')], max_length=24),
        ),
    ]
