# Adds the home-page copy/link keys (archetype-pal/frontend#183) and seeds them
# with the Models of Authority text the frontend previously hard-coded, so the
# live deployment renders exactly as before; other deployments edit them under
# Backoffice → Translations. get_or_create, so an admin's edits are never
# overwritten. The frontend's DEFAULT_MODEL_LABELS holds project-neutral
# fallbacks for these keys instead — they only show if a row is missing.
# Generated by Django 6.1.1 on 2026-09-30 09:44

from django.db import migrations, models


def _same(text):
    return {"en": text, "fr": text, "de": text}


HOME_LABELS = {
    "siteDescription": {
        "en": (
            "Scottish Charters and the Emergence of Government 1100-1250 – a resource for the study of the "
            "contents, script and physical appearance of the corpus of Scottish charters."
        ),
        "fr": (
            "Les chartes écossaises et l'émergence du gouvernement, 1100–1250. Une ressource pour l'étude du "
            "contenu, de l'écriture et de l'aspect physique du corpus des chartes écossaises."
        ),
        "de": (
            "Scottish Charters and the Emergence of Government, 1100–1250. Eine Ressource zur Erforschung von "
            "Inhalt, Schrift und äußerem Erscheinungsbild des Korpus schottischer Urkunden."
        ),
    },
    "homeHeroEyebrow": {"en": "1100–1250 \u00a0·\u00a0 Scotland", "fr": "1100–1250 \u00a0·\u00a0 Écosse", "de": "1100–1250 \u00a0·\u00a0 Schottland"},
    "homeHeroTitle": _same("Models of"),
    "homeHeroTitleEmphasis": _same("Authority"),
    "homeHeroSubtitle": {
        "en": (
            "Scottish Charters and the Emergence of Government — a resource for the study of the contents, "
            "script and physical appearance of the surviving charter corpus."
        ),
        "fr": (
            "Les chartes écossaises et l'émergence du gouvernement — une ressource pour l'étude du contenu, "
            "de l'écriture et de l'aspect physique du corpus des chartes conservées."
        ),
        "de": (
            "Scottish Charters and the Emergence of Government — eine Ressource zur Erforschung von Inhalt, "
            "Schrift und äußerem Erscheinungsbild des überlieferten Urkundenkorpus."
        ),
    },
    "homeAboutUrl": _same("/about/about-models-of-authority"),
    "homeCardManuscriptsTitle": {
        "en": "Charter Manuscripts",
        "fr": "Manuscrits de chartes",
        "de": "Urkundenhandschriften",
    },
    "homeCardManuscriptsDesc": {
        "en": "Browse and search the corpus of surviving Scottish charters from the twelfth and thirteenth centuries.",
        "fr": "Parcourez et recherchez le corpus des chartes écossaises survivantes des XIIe et XIIIe siècles.",
        "de": (
            "Durchsuchen Sie den Korpus der überlieferten schottischen Urkunden aus dem zwölften und "
            "dreizehnten Jahrhundert."
        ),
    },
    "homeCardHandsTitle": {"en": "Scribal Hands", "fr": "Mains scribes", "de": "Schreiberhände"},
    "homeCardHandsDesc": {
        "en": (
            "Explore the handwriting of the scribes who wrote these charters and trace connections between "
            "documents."
        ),
        "fr": (
            "Explorez l'écriture des scribes qui ont rédigé ces chartes et tracez les connexions entre les "
            "documents."
        ),
        "de": (
            "Erforschen Sie die Handschrift der Schreiber, die diese Urkunden verfasst haben, und verfolgen Sie "
            "Verbindungen zwischen Dokumenten."
        ),
    },
    "homeCardContextTitle": {"en": "Historical Context", "fr": "Contexte historique", "de": "Historischer Kontext"},
    "homeCardContextDesc": {
        "en": "Understand how charters shaped the emergence of government in medieval Scotland.",
        "fr": "Comprenez comment les chartes ont façonné l'émergence du gouvernement dans l'Écosse médiévale.",
        "de": (
            "Verstehen Sie, wie Urkunden die Entstehung der Regierung im mittelalterlichen Schottland geprägt "
            "haben."
        ),
    },
    "homeContextUrl": _same("/about/historical-context"),
    # A quotation, so it stays verbatim in every locale (as it rendered before).
    "homeQuote": _same(
        "“Government as we recognise it today first emerged in Western Europe in the twelfth century. One of "
        "the cardinal points on which our understanding of this development turns is the evidence of charters.”"
    ),
    "homeQuoteLinkLabel": {
        "en": "Read more about the historical context",
        "fr": "En savoir plus sur le contexte historique",
        "de": "Mehr über den historischen Kontext lesen",
    },
}


def seed_home_labels(apps, schema_editor):
    SiteLabel = apps.get_model("common", "SiteLabel")
    for key, value in HOME_LABELS.items():
        SiteLabel.objects.get_or_create(key=key, defaults={"value": value})


def unseed_home_labels(apps, schema_editor):
    SiteLabel = apps.get_model("common", "SiteLabel")
    SiteLabel.objects.filter(key__in=HOME_LABELS).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_seed_branding_and_header_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelabel',
            name='key',
            field=models.CharField(choices=[('historicalItem', 'Historical Item'), ('catalogueNumber', 'Catalogue Number'), ('position', 'Position'), ('date', 'Date'), ('appManuscripts', 'App Name: Manuscripts'), ('fieldHairType', 'Field: Hair Type'), ('fieldShelfmark', 'Field: Shelfmark'), ('fieldDateMinWeight', 'Field: Date Min Weight'), ('fieldDateMaxWeight', 'Field: Date Max Weight'), ('searchCategoryImages', 'Search Category: Images'), ('searchCategoryScribes', 'Search Category: Scribes'), ('searchCategoryHands', 'Search Category: Hands'), ('searchCategoryGraphs', 'Search Category: Graphs'), ('searchCategoryTexts', 'Search Category: Texts'), ('searchCategoryClauses', 'Search Category: Clauses'), ('searchCategoryPeople', 'Search Category: People'), ('searchCategoryPlaces', 'Search Category: Places'), ('siteTitle', 'Site Title'), ('siteTagline', 'Site Tagline'), ('footerLine1', 'Footer Line 1'), ('footerLine2', 'Footer Line 2'), ('footerBottomLine', 'Footer Bottom Line'), ('siteDescription', 'Site Description'), ('homeHeroEyebrow', 'Home: Hero Eyebrow'), ('homeHeroTitle', 'Home: Hero Title'), ('homeHeroTitleEmphasis', 'Home: Hero Title (Emphasised Line)'), ('homeHeroSubtitle', 'Home: Hero Subtitle'), ('homeAboutUrl', 'Home: About the Project Link'), ('homeCardManuscriptsTitle', 'Home: Manuscripts Card Title'), ('homeCardManuscriptsDesc', 'Home: Manuscripts Card Description'), ('homeCardHandsTitle', 'Home: Hands Card Title'), ('homeCardHandsDesc', 'Home: Hands Card Description'), ('homeCardContextTitle', 'Home: Context Card Title'), ('homeCardContextDesc', 'Home: Context Card Description'), ('homeContextUrl', 'Home: Context Link'), ('homeQuote', 'Home: Quote'), ('homeQuoteLinkLabel', 'Home: Quote Link Label')], max_length=64, unique=True),
        ),
        migrations.RunPython(seed_home_labels, unseed_home_labels),
    ]
