# Generated by Django 6.1.1 on 2026-10-01 14:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='common_place_name_ci_unique'),
        ),
    ]
