# Generated by Django 6.1 on 2026-09-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('allowed_tools', models.JSONField(default=list)),
                ('daily_run_quota', models.PositiveIntegerField(default=200)),
                ('max_turns', models.PositiveSmallIntegerField(default=8, help_text='Tool-calling turns before the loop is cut off.')),
                ('model_name', models.CharField(blank=True, default='', help_text='Provider model slug; blank uses the default.', max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service identities',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('citations', models.JSONField(default=list)),
                ('tool_calls', models.JSONField(default=list)),
                ('turns', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('refused', 'Refused'), ('failed', 'Failed'), ('exhausted', 'Turn limit reached')], db_index=True, max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('cost_micros', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agents.serviceidentity')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['identity', 'created'], name='agentrun_identity_created_idx')],
            },
        ),
    ]
