# Generated by Django 6.1 on 2026-09-08 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0027_embed_text_region_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_size', models.BigIntegerField()),
                ('chunk_size', models.PositiveIntegerField()),
                ('received_chunks', models.JSONField(blank=True, default=list)),
                ('destination_path', models.CharField(max_length=200)),
                ('locus', models.CharField(blank=True, default='', max_length=72)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('assembled', 'Assembled'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manuscripts.itemimage')),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='manuscripts.itempart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', 'created'], name='uploads_ima_status_810d15_idx')],
            },
        ),
    ]
