# Generated by Django 6.1.1 on 2026-09-12 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0027_embed_text_region_links'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='imageuploadsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'uploading', 'assembled', 'processing'))), fields=('destination_path',), name='uploads_one_active_session_per_destination'),
        ),
    ]
