paths:
  /api/v1/media/carousel-items/:
    get:
      operationId: carousel-items-list
      responses:
        200:
          description: List of carousel items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/carouselItem'
      
      tags:
        - Media & publications
  /api/v1/media/events/:
    get:
      operationId: events-list
      responses:
        200:
          description: List of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                  previous:
                    type: string
                    format: uri
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/eventListItem'
      tags:
        - Media & publications
  /api/v1/media/events/{slug}/:
    get:
      operationId: events-detail
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventDetailItem'
      tags:
        - Media & publications
  /api/v1/media/management/publications/:
    get:
      operationId: management-publications-list
      security:
        - api_key: []
      responses:
        200:
          description: List publications for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/publicationManagementItem'
      tags:
        - media-management
    post:
      operationId: management-publications-create
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publicationManagementWrite'
      responses:
        201:
          description: Created publication.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicationManagementItem'
      tags:
        - media-management
  /api/v1/media/management/events/:
    get:
      operationId: management-events-list
      security:
        - api_key: []
      responses:
        200:
          description: List events for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/eventDetailItem'
      tags:
        - media-management
  /api/v1/media/management/comments/:
    get:
      operationId: management-comments-list
      security:
        - api_key: []
      responses:
        200:
          description: List comments for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/commentManagementItem'
      tags:
        - media-management
  /api/v1/media/management/carousel-items/:
    get:
      operationId: management-carousel-items-list
      security:
        - api_key: []
      responses:
        200:
          description: List carousel items for management.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/carouselManagementItem'
      tags:
        - media-management
  /api/v1/media/publications/:
    get:
      operationId: publications-list
      parameters:
        - name: is_blog_post
          in: query
          required: false
          schema:
            type: boolean
        - name: is_news
          in: query
          required: false
          schema:
            type: boolean
        - name: is_featured
          in: query
          required: false
          schema:
            type: boolean
        - name: recent_posts
          in: query
          required: false
          schema:
            type: boolean
          description: When set to true, returns the 5 most recent posts ordered by their `published_at` field, regardless of any category filters.
      responses:
        200:
          description: No response body
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                  previous:
                    type: string
                    format: uri
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/publicationListItem'
      tags:
        - Media & publications
  /api/v1/media/publications/{slug}/:
    get:
      operationId: publications-detail
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicationDetailItem'
      tags:
        - Media & publications
components:
  schemas:
    carouselItem:
      type: object
      properties:
        title:
          type: string
        image:
          type: string
        link:
          type: string
    eventListItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
    eventDetailItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
    publicationListItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        number_of_comments:
          type: integer
        published_at:
          type: string
          format: date-time
        preview:
          type: string
    publicationDetailItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        number_of_comments:
          type: integer
        published_at:
          type: string
          format: date-time
        content:
          type: string
        comments:
          type: array
          items:
            type: object
            properties:
              author_name:
                type: string
              content:
                type: string
              created_at:
                type: string
                format: date-time
    publicationManagementItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        content:
          type: string
        preview:
          type: string
        author:
          type: integer
          nullable: true
        author_name:
          type: string
          nullable: true
        status:
          type: string
        is_blog_post:
          type: boolean
        is_news:
          type: boolean
        is_featured:
          type: boolean
        allow_comments:
          type: boolean
        comment_count:
          type: integer
    publicationManagementWrite:
      type: object
      properties:
        title:
          type: string
        slug:
          type: string
        content:
          type: string
        preview:
          type: string
        status:
          type: string
        is_blog_post:
          type: boolean
        is_news:
          type: boolean
        is_featured:
          type: boolean
        allow_comments:
          type: boolean
    commentManagementItem:
      type: object
      properties:
        id:
          type: integer
        post:
          type: integer
        post_title:
          type: string
        content:
          type: string
        author_name:
          type: string
        author_email:
          type: string
        author_website:
          type: string
        is_approved:
          type: boolean
    carouselManagementItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        url:
          type: string
        image:
          type: string
        ordering:
          type: integer
tags:
  - name: events
  - name: Media & publications
  - name: media-management
