# Generated by Django 6.0.6 on 2026-07-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.JSONField(blank=True, default=dict, help_text='Title per language, e.g. {"en": "...", "fr": "..."}')),
                ('content', models.JSONField(blank=True, default=dict, help_text='HTML content per language, e.g. {"en": "...", "fr": "..."}')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordering within the About sidebar/menu.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
